name: "godot-ci export"
on: 
  pull_request:
    branches:
      - main

env:
  GODOT_VERSION: 4.4
  EXPORT_NAME: 
  PROJECT_PATH: 

jobs:
  export-windows:
   name: Windows Export
   runs-on: ubuntu-latest
   container:
     image: barichello/godot-ci:4.4
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         lfs: true
     - name: Setup
       run: |
         mkdir -v -p ~/.local/share/godot/export_templates/
         mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
     - name: Windows Build
       run: |
         mkdir -v -p build/windows
         cd $PROJECT_PATH
         godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
     - name: Upload Artifact
       uses: actions/upload-artifact@v4.4.3
       with:
         name: windows
         path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: linux
          path: build/linux

  export-mac:
   name: Mac Export
   runs-on: ubuntu-latest
   container:
     image: barichello/godot-ci:4.4
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         lfs: true
     - name: Setup
       run: |
         mkdir -v -p ~/.local/share/godot/export_templates/
         mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
     - name: Mac Build
       run: |
         mkdir -v -p build/mac
         cd $PROJECT_PATH
         godot --headless --verbose --export-release "Mac OSX" ../build/mac/$EXPORT_NAME.zip
     - name: Upload Artifact
       uses: actions/upload-artifact@v4.4.3
       with:
         name: mac
         path: build/mac
  
  export-web:
   name: Web Export
   runs-on: ubuntu-latest
   container:
     image: barichello/godot-ci:4.4
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         lfs: true
     - name: Setup
       run: |
         mkdir -v -p ~/.local/share/godot/export_templates/
         mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
     - name: Web Build
       run: |
         mkdir -v -p build/web
         cd $PROJECT_PATH
         godot --headless --verbose --export-release "Web" ../build/web/index.html
     - name: Upload Artifact
       uses: actions/upload-artifact@v4.4.3
       with:
         name: web
         path: build/web